# ref: https://help.github.com/en/actions/building-actions/metadata-syntax-for-github-actions
name: Maven Version Update Action
description: A simple GitHub Action to update the pom version of Maven projects with release and next development version with tagging.

author: Michael Stähler

branding:
  color: blue
  icon: git-commit

inputs:
  github-token:
    description: 'A GitHub auth token to commit the updated version'
    required: true
  git-username:
    description: 'The name to use for the version update commit'
    required: true
    default: github-actions-bot
  git-email:
    description: 'The email address used to create the update version commit'
    required: true
    default: github-actions-bot@users.noreply.github.com

outputs:
  release-version:
    description: 'The updated release version which has been tagged'
    value: ${{ steps.release-version.outputs.release-version }}
  next-develop-version:
    description: 'The next development version (SNAPSHOT)'
    value: ${{ steps.next-dev-version.outputs.next-develop-version }}

runs:
  using: "composite"
  steps:
    - name: Update Maven Version
      env:
        GITHUB_USERNAME: ${{ inputs.git-username }}
        GITHUB_PASSWORD: ${{ inputs.github-token }}
        GITHUB_EMAIL: ${{ inputs.git-email }}
      shell: bash
      run: ${{github.action_path}}/update-version.sh -gu=$GITHUB_USERNAME -gp=$GITHUB_PASSWORD

    - name: Set output for release version
      id: release-version
      shell: bash
      run: echo ::set-output name=release-version::$(cat release_version.txt)

    - name: Set output for release version
      id: next-dev-version
      shell: bash
      run: echo ::set-output name=next-develop-version::$(cat next_dev_version.txt)

    - name: Print release version
      shell: bash
      run: "echo 'release version is ${{ steps.release-version.outputs.release-version }}'"

    - name: Print next development version
      shell: bash
      run: "echo 'next dev version is ${{ steps.next-dev-version.outputs.next-develop-version }}'"
